# Generated by Django 4.2.6 on 2023-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_telebot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telebot',
            name='user_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='telebot',
            name='user_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='telebot',
            name='user_sname',
            field=models.CharField(max_length=16),
        ),
    ]
