# Generated by Django 4.2.6 on 2023-11-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_telebot_user_id_alter_telebot_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telebot',
            old_name='user_id',
            new_name='user_id_telegram',
        ),
        migrations.RenameField(
            model_name='telebot',
            old_name='user_name',
            new_name='user_name_client',
        ),
        migrations.RenameField(
            model_name='telebot',
            old_name='user_sname',
            new_name='user_name_telegram',
        ),
        migrations.RenameField(
            model_name='telebot',
            old_name='user_time',
            new_name='username_telegram',
        ),
        migrations.AddField(
            model_name='telebot',
            name='user_time_client',
            field=models.CharField(default='df', max_length=36),
            preserve_default=False,
        ),
    ]
