# Generated by Django 4.2.6 on 2023-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_user_id_telebot_user_id_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telebot',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
