# Generated by Django 4.2.6 on 2023-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_telebot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telebot',
            name='trener',
            field=models.CharField(default='trener', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telebot',
            name='type_train',
            field=models.CharField(default='train', max_length=16),
            preserve_default=False,
        ),
    ]
