# Generated by Django 4.2.6 on 2023-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=16)),
                ('firstname', models.CharField(max_length=16)),
                ('patronymic', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=36, null=True, unique=True)),
                ('num_contract', models.PositiveIntegerField(max_length=8, unique=True)),
                ('num_membership', models.PositiveIntegerField(max_length=8, unique=True)),
                ('date_start_contract', models.DateField()),
                ('date_end_contract', models.DateField()),
                ('type_membership', models.CharField(max_length=16)),
                ('status_membership', models.CharField(max_length=16)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('passport', models.TextField(max_length=350)),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
