# Generated by Django 4.2.6 on 2023-10-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='num_contract',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_membership',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
