# Generated by Django 4.2.6 on 2023-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_journalvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalvisit',
            name='date_end_contract',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='date_end_visit',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='date_start_visit',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='locker_number',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='num_contract',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='status_membership',
        ),
        migrations.RemoveField(
            model_name='journalvisit',
            name='type_membership',
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_membership',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Не активный', 'Не активный')], max_length=16),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_membership',
            field=models.CharField(choices=[('Безлимитный', 'Безлимитный'), ('Лимитный', 'Лимитный')], max_length=16),
        ),
        migrations.AlterField(
            model_name='journalvisit',
            name='num_membership',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
