# Generated by Django 4.2.6 on 2023-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_journalvisit_date_end_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvisit',
            name='num_contract',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
