# Generated by Django 4.2.6 on 2023-10-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_journalvisit_num_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalvisit',
            name='num_contract',
        ),
    ]
