# Generated by Django 4.2.6 on 2023-10-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_journalvisit_num_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvisit',
            name='num_membership_id',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.PROTECT, to='users.client', to_field='num_membership'),
        ),
    ]
