# Generated by Django 4.2.6 on 2023-10-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_journalvisit_num_membership_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvisit',
            name='date_end_visit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='journalvisit',
            name='date_start_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
