# Generated by Django 4.2.6 on 2023-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_journalvisit_date_end_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvisit',
            name='date_end_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
