# Generated by Django 4.2.6 on 2023-10-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_journalvisit_date_end_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time_period',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=2),
        ),
    ]
