# Generated by Django 4.2.6 on 2023-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_client_time_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveJournalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_membership', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=8, null=True)),
                ('date_start_visit', models.DateTimeField(null=True)),
                ('date_end_visit', models.DateTimeField(null=True)),
                ('locker_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='time_period',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, unique=True),
        ),
    ]
