# Generated by Django 4.2.6 on 2023-10-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_archivejournalvisit_locker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejournalvisit',
            name='num_membership',
            field=models.CharField(max_length=8),
        ),
    ]
