# Generated by Django 4.2.6 on 2023-10-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_archivejournalvisit_num_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time_period',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
    ]
