# Generated by Django 4.2.6 on 2023-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_client_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_end_contract',
            field=models.DateField(blank=True),
        ),
    ]
