# Generated by Django 4.2.6 on 2023-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_client_date_end_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejournalvisit',
            name='date_start_visit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
