# Generated by Django 4.2.6 on 2023-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_archivejournalvisit_date_start_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejournalvisit',
            name='date_start_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
