# Generated by Django 4.2.6 on 2023-10-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_archivejournalvisit_date_start_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastnameTrener', models.CharField(max_length=16)),
                ('firstnameTrener', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('type_trains', models.CharField(choices=[('Персональные', 'Персональные'), ('Групповые', 'Групповые')], max_length=16)),
                ('photo', models.ImageField(default='default.jpg', upload_to='train_pics')),
            ],
        ),
    ]
