# Generated by Django 4.2.6 on 2023-10-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_trener'),
    ]

    operations = [
        migrations.AddField(
            model_name='trener',
            name='adwards',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
