# Generated by Django 4.2.6 on 2023-10-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_trener_adwards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_or_fio', models.CharField(max_length=48)),
                ('type_trains', models.CharField(choices=[('Персональная', 'Персональная'), ('Групповая', 'Групповая')], max_length=16)),
                ('dateTime', models.DateField()),
                ('visited', models.BooleanField(default=False)),
                ('trener', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.trener')),
            ],
        ),
    ]
