# Generated by Django 4.2.6 on 2023-10-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='trener',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.trener'),
        ),
    ]
