# Generated by Django 4.2.6 on 2023-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_train_id_alter_train_trener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
