# Generated by Django 4.2.6 on 2023-10-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_train_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='trener',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.trener'),
        ),
    ]
