# Generated by Django 4.2.6 on 2023-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_train_id_alter_train_trener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='trener',
        ),
        migrations.AddField(
            model_name='train',
            name='trener',
            field=models.ManyToManyField(to='users.trener'),
        ),
    ]
