# Generated by Django 4.2.6 on 2023-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_train_trener_train_trener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time_period',
            field=models.IntegerField(choices=[(1, 1), (3, 3), (6, 6), (12, 12)], default=1),
        ),
    ]
