# Generated by Django 4.2.6 on 2023-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_client_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_membership',
            field=models.CharField(choices=[('Безлимитный', 'Безлимитный'), ('Безлимитный', 'Безлимитный')], max_length=16),
        ),
    ]
