# Generated by Django 4.2.6 on 2023-11-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_client_type_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_membership',
            field=models.CharField(choices=[('Б', 'Б'), ('е', 'е'), ('з', 'з'), ('л', 'л'), ('и', 'и'), ('м', 'м'), ('и', 'и'), ('т', 'т'), ('н', 'н'), ('ы', 'ы'), ('й', 'й')], max_length=16),
        ),
    ]
