# Generated by Django 4.2.5 on 2023-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='adres',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='userdata',
            name='news',
            field=models.BooleanField(default=True),
        ),
    ]
